"""phase_3_models

Revision ID: f63427a0f2a9
Revises: d22fd96c7bfe
Create Date: 2026-05-07 15:12:56.085824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f63427a0f2a9'
down_revision: Union[str, Sequence[str], None] = 'd22fd96c7bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.Column('lab_version_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('checker_provider', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['lab.id'], ),
    sa.ForeignKeyConstraint(['lab_version_id'], ['labversion.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['labsession.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_id'), 'submission', ['id'], unique=False)
    op.create_table('submissionresultitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('check_key', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('score_awarded', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissionresultitem_id'), 'submissionresultitem', ['id'], unique=False)
    
    with op.batch_alter_table('labsession') as batch_op:
        batch_op.add_column(sa.Column('lab_version_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('runtime_provider', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('workspace_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('failure_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('metadata_json', sa.JSON(), nullable=True))
        batch_op.create_foreign_key('fk_labsession_lab_version', 'labversion', ['lab_version_id'], ['id'])
        batch_op.drop_column('score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labsession') as batch_op:
        batch_op.add_column(sa.Column('score', sa.FLOAT(), nullable=True))
        batch_op.drop_constraint('fk_labsession_lab_version', type_='foreignkey')
        batch_op.drop_column('metadata_json')
        batch_op.drop_column('failure_reason')
        batch_op.drop_column('stopped_at')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('expires_at')
        batch_op.drop_column('last_activity_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('workspace_url')
        batch_op.drop_column('runtime_provider')
        batch_op.drop_column('lab_version_id')
        
    op.drop_index(op.f('ix_submissionresultitem_id'), table_name='submissionresultitem')
    op.drop_table('submissionresultitem')
    op.drop_index(op.f('ix_submission_id'), table_name='submission')
    op.drop_table('submission')
    # ### end Alembic commands ###
